# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-04 21:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20170705_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the object was created.'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Key-value store suitable for storing arbitrary information not covered elsewhere.'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the object was created.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Key-value store suitable for storing arbitrary information not covered elsewhere.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the object was created.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Key-value store suitable for storing arbitrary information not covered elsewhere.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the object was created.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Key-value store suitable for storing arbitrary information not covered elsewhere.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated.'),
        ),
    ]
