# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20170804_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='index_name',
            field=models.CharField(db_index=True, help_text='Concatenated name for search purposes.', max_length=400, null=True),
        ),
    ]
