# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='flavor_text',
            field=models.CharField(blank=True, help_text="Just like on a trading card, this is the text to give someone an idea of a person's character.", max_length=2000),
        ),
    ]
