language: python

sudo: false

cache:
  - pip

python:
  - "2.7"

env:
  global:
    - CODACY_PROJECT_TOKEN=b31441a7f46b40a98b7fca4e921de479
  matrix:
    - DJANGO_VERSION="1.11.*"

install:
 - pip install -r requirements.txt
 - pip uninstall -y Django
 - pip install -q Django==$DJANGO_VERSION
 - pip install codacy-coverage
 - pip list

before_script:
  - psql -c 'create database access_mo_django;' -U postgres
  - cp am/am/settings_local.py.template am/am/settings_local.py
  - python am/manage.py migrate

script:
  - make test

after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml

addons:
  postgresql: "9.4"

notifications:
  slack: accessmissouri:RBS1G1vbgVLJalHdSL1s82Zh
