language: python

sudo: false

cache:
  - pip

python:
  - "2.7"
  - "3.5"

env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11rc1

install:
 - pip install -r requirements.txt
 - pip uninstall -y Django
 - pip install -q Django==$DJANGO_VERSION

before_script:
  - psql -c 'create database access_mo_django;' -U postgres
  - psql -c "CREATE EXTENSION postgis;" -U postgres -d access_mo_django
  - cd am
  - cp am/settings_local.py.template am/settings_local.py

script:
  - flake8 am
  - python manage.py migrate
  - coverage run manage.py test house_scraper
  - coverage run manage.py test senate_scraper

after_success:
  - coveralls

addons:
  postgresql: "9.4"
