language: python

sudo: false

cache:
  - pip

python:
  - "2.7"
  - "3.5"

env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11b

before_script:
  - psql -c 'create database access_mo_django;' -U postgres
  - psql -c "CREATE EXTENSION postgis;" -U postgres -d access_mo_django

script:
  - flake8 am
  # - coverage run manage.py test senate_scraper
  # - coverage run manage.py test house_scraper

after_success:
  - coveralls

addons:
  postgresql: "9.4"
