# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='ocd_boundary_id',
            field=models.CharField(default='', help_text="Open Civic Data's unique area boundary identifier.", max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='district',
            name='ocd_division_id',
            field=models.CharField(help_text="Open Civic Data's unique division identifier.", max_length=300),
        ),
    ]
