# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 14:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0004_person_index_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text=b'Date and time when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text=b'Date and time when the object was last updated.')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text=b'Key-value store suitable for storing arbitrary information not covered elsewhere.')),
                ('name', models.CharField(max_length=512)),
                ('summary', models.TextField(blank=True, null=True)),
                ('text', models.TextField()),
                ('source_url', models.URLField(blank=True, max_length=512, null=True)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_bills', to='general.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
