# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeentity',
            name='occupation',
            field=models.CharField(blank=True, help_text='Occupation, if person.', max_length=150, null=True),
        ),
    ]
