# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-22 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20180625_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentity',
            name='mec_id',
            field=models.CharField(blank=True, db_index=True, help_text='Missouri Ethics Commission ID number.', max_length=128),
        ),
        migrations.AlterField(
            model_name='financeentity',
            name='name',
            field=models.CharField(db_index=True, help_text='Readable name if Company or Committee.', max_length=300),
        ),
    ]
