# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 15:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20180427_1115'),
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallotMeasure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text=b'Date and time when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text=b'Date and time when the object was last updated.')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text=b'Key-value store suitable for storing arbitrary information not covered elsewhere.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the measure, as referred to on the ballot.', max_length=300)),
                ('ballot_title', models.TextField(blank=True, help_text='The way the measure will be explained to constituents above their vote.')),
                ('ballot_summary', models.TextField(blank=True, help_text='The extended summary available to constituents on election day.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text=b'Date and time when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text=b'Date and time when the object was last updated.')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text=b'Key-value store suitable for storing arbitrary information not covered elsewhere.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Human-friendly name of the contest or race.', max_length=300)),
                ('election', models.ForeignKey(help_text='The full slate of contests this contest is or was a part of.', on_delete=django.db.models.deletion.CASCADE, related_name='contests', related_query_name='contest', to='elections.Election')),
                ('jurisdiction', models.ForeignKey(help_text='Where is this race taking place?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='election_contests', related_query_name='election_contest', to='geo.District')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='contest',
            name='election',
        ),
        migrations.DeleteModel(
            name='Contest',
        ),
    ]
