# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20181102_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='election',
            field=models.ForeignKey(help_text='The full slate of contests this contest is or was a part of.', on_delete=django.db.models.deletion.CASCADE, related_name='races', related_query_name='race', to='elections.Election'),
        ),
    ]
