# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20181102_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='jurisdiction',
            field=models.ForeignKey(help_text='Where is this race taking place?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='election_races', related_query_name='election_race', to='geo.District'),
        ),
    ]
