# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 03:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text=b'Date and time when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text=b'Date and time when the object was last updated.')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text=b'Key-value store suitable for storing arbitrary information not covered elsewhere.')),
                ('identifier', models.CharField(help_text="Identifier for the bill, as assigned by the Clerk's office.", max_length=100)),
                ('title', models.TextField(help_text='The current title of the bill.')),
                ('lr_number', models.CharField(help_text='Legislative Research (?) number.', max_length=100)),
                ('proposed_effective_date', models.DateField(help_text='Proposed date when the bill, if passed, would go into effect.', null=True)),
                ('last_action_date', models.DateField(help_text='Date when the last action on bill happened.', null=True)),
                ('last_action_description', models.CharField(help_text="Description of the bill's last action.", max_length=300, null=True)),
                ('calendar_position', models.CharField(help_text='Current position of the bill on the legislative calendar.', max_length=300, null=True)),
                ('from_organization', models.ForeignKey(help_text='Reference to the Organization (typically a legislative chamber) wherein the bill originated.', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='general.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='BillAbstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text=b'Date and time when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text=b'Date and time when the object was last updated.')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text=b'Key-value store suitable for storing arbitrary information not covered elsewhere.')),
                ('abstract', models.TextField(help_text='Text of the abstract.')),
                ('note', models.TextField(blank=True, help_text='A note about the origin of the summary.')),
                ('bill', models.ForeignKey(help_text='Reference to the bill with the abstract.', on_delete=django.db.models.deletion.CASCADE, related_name='abstracts', to='legislative.Bill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text=b'Date and time when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text=b'Date and time when the object was last updated.')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text=b'Key-value store suitable for storing arbitrary information not covered elsewhere.')),
                ('description', models.TextField(help_text='Description of the action.')),
                ('date', models.DateField(help_text='Date when the action occurred.')),
                ('order', models.PositiveIntegerField(help_text="Order of the action in the Bill's activity history.")),
                ('bill', models.ForeignKey(help_text='Reference to the bill that was acted on.', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='legislative.Bill')),
                ('organization', models.ForeignKey(help_text='Reference to the Organization that the action took place within.', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='general.Organization')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BillAmendment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text=b'Date and time when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text=b'Date and time when the object was last updated.')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text=b'Key-value store suitable for storing arbitrary information not covered elsewhere.')),
                ('status', models.CharField(help_text='Status of the bill amendment (e.g., "Distributed", "Withdrawn").', max_length=300)),
                ('url', models.URLField(help_text='Official URL where the text of the amendments is available.', max_length=2000)),
                ('bill', models.ForeignKey(help_text='Reference to the Bill to which the amendment was proposed.', on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='legislative.Bill')),
                ('member', models.ForeignKey(help_text='Reference to the member who proposed the bill amendment.', on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='general.Membership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillSponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text=b'Date and time when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text=b'Date and time when the object was last updated.')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text=b'Key-value store suitable for storing arbitrary information not covered elsewhere.')),
                ('primary', models.BooleanField(default=False, help_text='Indicates the member is a primary sponsor of the Bill.')),
                ('sponsored_at', models.DateTimeField(help_text='Date and time when the member sponsored the bill.', null=True)),
                ('bill', models.ForeignKey(help_text='Reference to the sponsored Bill.', on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='legislative.Bill')),
                ('member', models.ForeignKey(help_text='Reference to the member who sponsored the Bill.', on_delete=django.db.models.deletion.CASCADE, related_name='bill_sponsorships', to='general.Membership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text=b'Date and time when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text=b'Date and time when the object was last updated.')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text=b'Key-value store suitable for storing arbitrary information not covered elsewhere.')),
                ('title', models.TextField(help_text='Alternate title for the bill.')),
                ('note', models.TextField(blank=True, help_text='A note describing the origin of the title.')),
                ('bill', models.ForeignKey(help_text='Reference to the bill with the alternate title.', on_delete=django.db.models.deletion.CASCADE, related_name='other_titles', to='legislative.Bill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text=b'Date and time when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text=b'Date and time when the object was last updated.')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text=b'Key-value store suitable for storing arbitrary information not covered elsewhere.')),
                ('note', models.CharField(help_text='Note describing the version.', max_length=300)),
                ('date', models.DateField(help_text='Date when the version was published.')),
                ('url', models.URLField(help_text='Official URL where the text of the version is available.', max_length=2000)),
                ('bill', models.ForeignKey(help_text='Reference to the Bill to which the version belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='legislative.Bill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegislativeSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text=b'Date and time when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text=b'Date and time when the object was last updated.')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text=b'Key-value store suitable for storing arbitrary information not covered elsewhere.')),
                ('name', models.CharField(help_text='Full official name for the Legislative Session.', max_length=300)),
                ('classification', models.CharField(choices=[('E', 'Extraordinary'), ('R', 'Regular')], help_text='Classifies the Legislative Session (e.g., "Regular" or "Extraordinary").', max_length=100)),
                ('start_date', models.DateField(help_text='Date that the Legislative Session starts.')),
                ('end_date', models.DateField(help_text='Date that the Legislative Session ends, if known.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='legislative_session',
            field=models.ForeignKey(help_text='Reference to the Legislative Session in which the Bill was considered.', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='legislative.LegislativeSession'),
        ),
        migrations.AlterIndexTogether(
            name='bill',
            index_together=set([('legislative_session', 'from_organization', 'identifier')]),
        ),
    ]
