# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0002_auto_20170705_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislativesession',
            name='web_session_type_code',
            field=models.CharField(blank=True, help_text='Used by scraper - type code for params.', max_length=12, null=True),
        ),
    ]
