# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0004_auto_20170804_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislativesession',
            name='start_date',
            field=models.DateField(help_text='Date that the Legislative Session starts.', null=True),
        ),
    ]
