# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0006_auto_20171016_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billaction',
            name='organization',
            field=models.ForeignKey(help_text='Reference to the Organization that the action took place within.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='general.Organization'),
        ),
    ]
