# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 18:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20170804_2100'),
        ('legislative', '0008_auto_20171113_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text=b'Date and time when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text=b'Date and time when the object was last updated.')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text=b'Key-value store suitable for storing arbitrary information not covered elsewhere.')),
                ('issue', models.CharField(help_text='What the vote was on - as described in journal.', max_length=512)),
                ('yes', models.IntegerField(default=0)),
                ('no', models.IntegerField(default=0)),
                ('did_not_vote', models.IntegerField(default=0)),
                ('absent', models.IntegerField(default=0)),
                ('did_pass', models.BooleanField(default=False)),
                ('date', models.DateField(help_text='Date the vote was taken.')),
                ('bill', models.ForeignKey(help_text='Reference to the bill being voted on.', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='legislative.Bill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text=b'Date and time when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text=b'Date and time when the object was last updated.')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text=b'Key-value store suitable for storing arbitrary information not covered elsewhere.')),
                ('opinion', models.CharField(help_text='What the person actually voted.', max_length=12)),
                ('bill_vote', models.ForeignKey(help_text='Reference to the broad vote in question.', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='legislative.BillVote')),
                ('person', models.ForeignKey(help_text='Reference to the person casting the vote.', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='general.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
