# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20170804_2100'),
        ('legislative', '0009_billvote_personvote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billsponsorship',
            options={'ordering': ['-sponsored_at', 'primary']},
        ),
        migrations.AlterModelOptions(
            name='billvote',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='billsponsorship',
            name='person',
            field=models.ForeignKey(default=1, help_text='The person who sponsored the bill.', on_delete=django.db.models.deletion.CASCADE, related_name='bill_sponsorships', to='general.Person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billsponsorship',
            name='member',
            field=models.ForeignKey(help_text='Reference to the membership record for who sponsored the Bill.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_sponsorships', to='general.Membership'),
        ),
        migrations.AlterField(
            model_name='personvote',
            name='bill_vote',
            field=models.ForeignKey(help_text='Reference to the broad vote in question.', on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='legislative.BillVote'),
        ),
    ]
