# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0010_auto_20171117_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsponsorship',
            name='sponsored_at',
            field=models.DateField(help_text='Date and time when the member sponsored the bill.', null=True),
        ),
    ]
