# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 22:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0013_bodymembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text=b'Date and time when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text=b'Date and time when the object was last updated.')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text=b'Key-value store suitable for storing arbitrary information not covered elsewhere.')),
                ('type', models.CharField(max_length=140)),
                ('date', models.DateField()),
                ('state_url', models.URLField(max_length=2000)),
                ('ls_doc_id', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_versions', to='legislative.Bill')),
            ],
            options={
                'ordering': ['bill__name', '-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='bodymembership',
            options={'ordering': ['-session__name']},
        ),
    ]
