# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0014_auto_20171214_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billtext',
            options={'ordering': ['bill__identifier', '-date']},
        ),
        migrations.AddField(
            model_name='billtext',
            name='text_state_kw',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
