# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20180104_1623'),
        ('legislative', '0015_auto_20171215_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymembership',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.District'),
        ),
    ]
