# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0016_bodymembership_district'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-legislative_session__name', '-last_action_date', 'identifier']},
        ),
        migrations.AlterModelOptions(
            name='personvote',
            options={'ordering': ['-bill_vote__date']},
        ),
    ]
