# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0017_auto_20180419_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='calendar_position',
            field=models.CharField(blank=True, help_text='Current position of the bill on the legislative calendar.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='from_organization',
            field=models.ForeignKey(blank=True, help_text='Reference to the Organization (typically a legislative chamber) wherein the bill originated.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='general.Organization'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='lr_number',
            field=models.CharField(blank=True, help_text="First part of Legislative Reference number (before '.').", max_length=6, null=True, verbose_name='LR Number'),
        ),
    ]
