# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0019_bill_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billamendment',
            name='member',
            field=models.ForeignKey(help_text='Reference to the member who proposed the bill amendment.', on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='legislative.BodyMembership'),
        ),
        migrations.AlterField(
            model_name='billsponsorship',
            name='member',
            field=models.ForeignKey(help_text='Reference to the membership record for who sponsored the Bill.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_sponsorships', to='legislative.BodyMembership'),
        ),
    ]
