# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0020_auto_20180424_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='personvote',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legislative.BodyMembership'),
        ),
        migrations.AlterField(
            model_name='bodymembership',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_memberships', to='geo.District'),
        ),
    ]
