# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0021_auto_20180427_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personvote',
            old_name='membership',
            new_name='member',
        ),
    ]
