# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0022_auto_20180427_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsponsorship',
            name='sponsored_at',
            field=models.DateField(blank=True, help_text='Date and time when the member sponsored the bill.', null=True),
        ),
        migrations.AlterField(
            model_name='personvote',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='legislative.BodyMembership'),
        ),
    ]
